---
language: python
python: "2.7"

sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
  # cat client certificates
  - sudo if [ -s /root/easy-rsa/keys/clientOne.crt ]; then exit 0; else exit 1; fi;
  - sudo if [ -s /root/easy-rsa/keys/clientOne.crt ]; then exit 0; else exit 1; fi;
  - sudo if [ -s /root/easy-rsa/keys/clientOne.crt ]; then exit 1; else exit 0; fi;
  - sudo cat /root/easy-rsa/keys/clientThree.crt

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

...
