---

# Block start add client
- block:

  - name: check for existing client certificate
    stat:
      path: "{{ easyrsa_dir }}/easy-rsa/keys/{{ client.name }}.crt"
    register: _client_crt

  - name: add client
    shell: |
      source ./vars
      export EASY_RSA="${EASY_RSA:-.}"
      "$EASY_RSA/pkitool" {{ client.name }}
    args:
      chdir: "{{ easyrsa_dir }}/easy-rsa/"
      executable: /bin/bash
    when: not _client_crt.stat.exists
    become: yes
    become_user: "{{ easyrsa_user }}"

  # Block condition add client
  when: ((client.state is defined and client.state == 'present') or client.state is not defined)
# Block end add client

# Block start remove client
- block:

  - name: remove client
    shell: |
      source ./vars
      export EASY_RSA="${EASY_RSA:-.}"
      "$EASY_RSA/revoke-full" {{ client.name }}
      export CLIENT={{ client.name }}
      rm -rf $KEY_DIR/$CLIENT*
    args:
      chdir: "{{ easyrsa_dir }}/easy-rsa/"
      executable: /bin/bash
    become: yes
    become_user: "{{ easyrsa_user }}"

  # Block condition remove client
  when: (client.state is defined and client.state == 'absent')
# Block end remove client

...
